version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: kg-recruitment
    container_name: kg_recruitment
    volumes:
      - .:/app # Mount the current directory to /app in the container
    working_dir: /app
    tty: true # Keep the terminal open